# Generated by Django 4.2.7 on 2025-10-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('carrera', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
    ]
